stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/devops-team/task-manager:$CI_COMMIT_REF_SLUG

test:
  stage: test
  image: python:3.13
  before_script:
    - pip install -r requirements.txt
  script:
    - python -m pytest tests/

build-docker:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - master

deploy-prod:
  stage: deploy
  image: alpine
  script:
    - echo "Deploy para produção"
    - echo "Implemente aqui seus comandos de deploy"
  when: manual
  only:
    - master
