stages:
  - security
  - stage
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/devops-team/task-manager:$CI_COMMIT_REF_SLUG
  STAGE_APP_URL: "http://stage.gitlab.example.com"
  ZAP_API_KEY: "$ZAP_API_KEY"

# Análise de Segurança
security-checks:
  stage: security
  image: python:3.9
  script:
    - pip install bandit
    - bandit -r . -f json -o bandit-report.json
    - pip install dependency-check
    - dependency-check --project "Task Manager" --scan . --format JSON --output dependency-check-report.json
  artifacts:
    paths:
      - bandit-report.json
      - dependency-check-report.json
    expire_in: 1 week

# Testes de Segurança Dinâmicos (DAST)
zap-scan:
  stage: security
  image: owasp/zap2docker-weekly
  script:
    - zap-baseline.py -t $STAGE_APP_URL -r zap-report.json
    - cat zap-report.json
  artifacts:
    paths:
      - zap-report.json
    expire_in: 1 week
  dependencies:
    - stage-deploy
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: on_success
      allow_failure: false

# Deploy em Estágio
stage-deploy:
  stage: stage
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
    - echo "Aplicação disponível em: $STAGE_APP_URL"
  environment:
    name: staging
    url: $STAGE_APP_URL
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: on_success
      allow_failure: false

# Deploy em Produção
prod-deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE:prod .
    - docker push $DOCKER_IMAGE:prod
    - echo "Aplicação disponível em produção"
  environment:
    name: production
    url: "http://prod.gitlab.example.com"
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: on_success
      allow_failure: false
