server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: task-manager
    static_configs:
      - targets: ["localhost"]
        labels:
          job: task-manager
          __path__: /var/log/task_manager/*.log

  - job_name: application
    static_configs:
      - targets: ["localhost"]
        labels:
          job: application
          __path__: /var/log/app/*.log

  - job_name: system
    static_configs:
      - targets: ["localhost"]
        labels:
          job: system
          __path__: /var/log/syslog

  - job_name: docker
    static_configs:
      - targets: ["localhost"]
        labels:
          job: docker
          __path__: /var/log/docker/*.log
