database: /app/task_manager.db
metrics:
  enabled:
    - name: sqlite_database_size_bytes
      description: Size of the database in bytes
    - name: sqlite_table_rows
      description: Number of rows in each table
      tables:
        - tasks
        - users
    - name: sqlite_table_size_bytes
      description: Size of each table in bytes
      tables:
        - tasks
        - users
    - name: sqlite_table_indexes
      description: Number of indexes per table
      tables:
        - tasks
        - users
    - name: sqlite_table_index_size_bytes
      description: Size of indexes per table
      tables:
        - tasks
        - users
    - name: sqlite_table_columns
      description: Number of columns per table
      tables:
        - tasks
        - users
