name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest tests/

    - name: Build Docker image
      run: |
        docker build -t task-manager:latest .

    - name: Run Docker Compose
      run: |
        docker-compose -f monitoring/docker-compose.yml up -d

    - name: Run Lint
      run: |
        pip install flake8
        flake8 .

    - name: Run Security Scan
      run: |
        pip install bandit
        bandit -r .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker tag task-manager:latest your-dockerhub-username/task-manager:latest
        docker push your-dockerhub-username/task-manager:latest
