name: Monitoring Pipeline

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  setup-monitoring:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker
      run: |
        sudo service docker start
        sudo usermod -aG docker $USER
        newgrp docker

    - name: Build Monitoring Stack
      run: |
        docker-compose -f monitoring/docker-compose.yml build

    - name: Start Monitoring Services
      run: |
        docker-compose -f monitoring/docker-compose.yml up -d

    - name: Verify Services
      run: |
        sleep 30  # Wait for services to start
        docker ps

    - name: Configure Grafana
      run: |
        sleep 30  # Wait for Grafana to be ready
        curl -u admin:admin -X POST -H "Content-Type: application/json" \
          http://localhost:3000/api/datasources \
          -d '{"name":"Loki","type":"loki","url":"http://loki:3100","access":"proxy"}'

    - name: Configure Prometheus
      run: |
        sleep 30  # Wait for Prometheus to be ready
        curl -X POST -H "Content-Type: application/json" \
          http://localhost:9090/api/v1/rules \
          -d '@monitoring/prometheus-task-manager-rules.yml'

    - name: Start Monitoring
      run: |
        echo "Monitoring services are now running and configured"
        echo "Access Grafana at: http://localhost:3000"
        echo "Access Prometheus at: http://localhost:9090"
        echo "Access Loki at: http://localhost:3100"
