name: Security Checks

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Diariamente à meia-noite

jobs:
  bandit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Bandit
      run: |
        pip install bandit
        bandit -r . -f json -o bandit-report.json
    
    - name: Upload Bandit Report
      uses: actions/upload-artifact@v4.1.1
      with:
        name: bandit-report
        path: bandit-report.json
        retention-days: 7

  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Dependency Check
      run: |
        pip install dependency-check
        dependency-check --project "Task Manager" --scan . --format JSON --output dependency-check-report.json
    
    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v4.1.1
      with:
        name: dependency-check-report
        path: dependency-check-report.json
        retention-days: 7

  notify:
    needs: [bandit, dependency-check]
    runs-on: ubuntu-latest
    
    steps:
    - name: Security Summary
      if: always()
      run: |
        echo "Security checks completed. Check artifacts for reports."