name: Security Checks

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Diariamente à meia-noite

env:
  CI: true
  CI_SERVER: "github"

jobs:
  bandit:
    runs-on: ubuntu-latest
    if: github.repository == 'your-username/your-repo-name'
    
    steps:
    - name: Debug Info
      run: |
        echo "Running Security Checks"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"
        echo "Event: ${{ github.event_name }}"
        echo "Workflow: ${{ github.workflow }}"

    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Run Bandit
      run: |
        pip install bandit
        bandit -r . -f json -o bandit-report.json
    
    - name: Upload Bandit Report
      uses: actions/upload-artifact@v3
      with:
        name: bandit-report
        path: bandit-report.json
        retention-days: 7

  dependency-check:
    runs-on: ubuntu-latest
    if: github.repository == 'your-username/your-repo-name'
    
    steps:
    - name: Debug Info
      run: |
        echo "Running Dependency Check"
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"
        echo "Event: ${{ github.event_name }}"
        echo "Workflow: ${{ github.workflow }}"

    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Run Dependency Check
      run: |
        pip install dependency-check
        dependency-check --project "Task Manager" --scan . --format JSON --output dependency-check-report.json
    
    - name: Upload Dependency Check Report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: dependency-check-report.json
        retention-days: 7

  notify:
    needs: [bandit, dependency-check]
    runs-on: ubuntu-latest
    if: github.repository == 'your-username/your-repo-name'
    
    steps:
    - name: Security Summary
      if: always()
      run: |
        echo "Security checks completed. Check artifacts for reports."
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"